G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&

G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&G&g&g&
